---
# Git URL and version to use, version must be a Git tag
netbox_version: v3.3.2
netbox_git_url: https://github.com/netbox-community/netbox.git

# Where to install Netbox
netbox_install_directory: /opt/netbox
netbox_virtualenv_path: "{{ netbox_install_directory }}/venv"

# Which user/group should own the files
netbox_user: netbox
netbox_group: netbox
netbox_user_home_directory: /home/netbox

# Mostly used for the first setup, superuser password still need to be set
netbox_superuser_username: admin
netbox_superuser_password: admin
netbox_superuser_email: admin@example.com

# Python local requirements to enable some features such as napalm or plugins
# netbox_local_requirements: []
netbox_local_requirements: 
  # - netbox-plugin-device-map
  # - netbox-topology-views
  # - nextbox_ui_plugin


# LDAP authentication
netbox_setup_ldap_auth: false
# LDAP configuration, can be used like
# netbox_ldap_config: |
#                     This is my configuration on multiple lines.
#                     That is pretty simple to do, but maybe painful?
# Example for LDAP configuration can be found at the following URL:
# http://netbox.readthedocs.io/en/latest/installation/ldap/
netbox_ldap_config: ""

# Systemd unit variables (configured by default)
netbox_setup_systemd: true
netbox_gunicorn_address: 127.0.0.1
netbox_gunicorn_port: 8001
netbox_gunicorn_workers_number: "{{ ansible_processor_vcpus + 1 }}"

# Web frontend variables (not configured by default)
netbox_setup_web_frontend: true

# Database related variables (password must be changed)
netbox_database: netbox
netbox_database_user: netbox
netbox_database_password: netbox
netbox_database_host: localhost

# Configuration
netbox_config:
  ALLOWED_HOSTS:
    - "*"

  MEDIA_ROOT: "{{ netbox_install_directory }}/netbox/media"
  REPORTS_ROOT: "{{ netbox_install_directory }}/netbox/reports"
  RQ_DEFAULT_TIMEOUT: 300

  PLUGINS: []
  # PLUGINS: ["netbox_topology_views", "netbox_device_map", "nextbox_ui_plugin"]

# Housekeeping
netbox_housekeeping: true
netbox_housekeeping_hour: 4
netbox_housekeeping_minute: 30

netbox_host: localhost


__netbox_python_packages:
  - python3.10
  - python3.10-dev
  - python3-venv
  - python3-pip
__netbox_postgresql_packages:
  - postgresql
  - libpq-dev
  - python3-psycopg2
__netbox_redis_packages:
  - redis-server

__netbox_other_packages:
  - git
  - libxml2-dev
  - libxslt1-dev
  - libffi-dev
  - libjpeg-dev
  - graphviz
  - libssl-dev

__netbox_ldap_packages:
  - libldap2-dev
  - libsasl2-dev

__netbox_web_frontend_packages:
  - apache2
  - apache2-utils
  - libapache2-mod-wsgi-py3

netbox_python_binary: /usr/bin/python3.10

netbox_postgresql_service: postgresql
netbox_postgresql_user: postgres

netbox_redis_service: redis-server
netbox_redis_configuration: /etc/redis/redis.conf

netbox_apache2_service: apache2
netbox_apache2_user: www-data
netbox_apache2_group: www-data
netbox_apache2_sites_available_path: /etc/apache2/sites-available
netbox_apache2_sites_enabled_path: /etc/apache2/sites-enabled
netbox_apache2_default_vhost: 000-default.conf
