---
# Copyright (c) 2018-2020 Guillaume Mazoyer under the GPL License
# Copyright (c) 2017-2018 Musee "lae" Ullah under the MIT License

- name: "install_task | Update repositories cache"
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: "install_task | Update all packages to their latest version"
  apt:
    name: "*"
    state: latest
  when: ansible_os_family == "Debian"

- name: "install_task | packages"
  apt: name={{item}} state=present
  with_items:
    - python3.10
    - python3.10-dev
    - python3-venv
    - python3-pip
    - postgresql
    - libpq-dev
    - python3-psycopg2
    - redis-server
    - git
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - libjpeg-dev
    - graphviz
    - libssl-dev
    - libldap2-dev
    - libsasl2-dev
    - apache2
    - apache2-utils
    - libapache2-mod-wsgi-py3



- name: install required packages
  ansible.builtin.package:
    name: "{{ __netbox_required_packages | flatten }}"
    state: present
  vars:
    __netbox_required_packages:
      - "{{ netbox_python_packages }}"
      - "{{ netbox_postgresql_packages }}"
      - "{{ netbox_redis_packages }}"
      - "{{ netbox_ldap_packages if netbox_setup_ldap_auth else [] }}"
      - "{{ netbox_other_packages }}"
      - "{{ netbox_web_frontend_packages if netbox_setup_web_frontend else [] }}"
  register: package_result
  until: package_result is success
