---
- name: enable required apache2 modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - headers
    - proxy
    - proxy_http
    - wsgi
    - ssl
  notify:
    - restart apache2

- name: remove default vhost
  ansible.builtin.file:
    path: "{{ netbox_apache2_sites_enabled_path }}/{{ netbox_apache2_default_vhost }}"
    state: absent
  notify:
    - restart apache2

- name: configure netbox vhost
  ansible.builtin.template:
    src: netbox_vhost.conf.j2
    dest: "{{ netbox_apache2_sites_available_path }}/netbox.conf"
    owner: "{{ netbox_apache2_user }}"
    group: "{{ netbox_apache2_group }}"
    mode: 0644

# - name: enable netbox vhost
#   ansible.builtin.file:
#     src: "{{ netbox_apache2_sites_available_path }}/netbox.conf"
#     dest: "{{ netbox_apache2_sites_enabled_path }}/netbox.conf"
#     state: link
#   notify:
#     - restart apache2
#   tags:
#   - configuration
